### ISSUE TITLE
unable to locate publishable resource

### ISSUE THREAD

**Issue by alexjqyi** [diglactic/laravel-breadcrumbs#1]
when I run 
`php artisan vendor:publish --tag=breadcrumbs-config`
I got 
`Unable to locate publishable resources.
Publishing complete.`

And I cannot found diglactic/laravel-breadcrumbs in my vendor folder after I run 
`composer require diglactic/laravel-breadcrumbs`   
and no error msg shown

Other info:
Laravel 7.24
php:7.4-fpm

Please kindly help, thanks a lot

**Comment by shengslogar** [comment]
Hi @alexjqyi, looks like `composer require` isn't running correctly because you should have files in your `vendor` folder and `vendor:publish` should also work as expected.

Could you post the console log when you run the first `composer require`?

**Comment by alexjqyi** [comment]
Issue fixed. It turn out to be caused by short of memory of vm. Thanks
