### ISSUE TITLE
"A facade root has not been set."

### ISSUE THREAD

**Issue by xtfer** [diglactic/laravel-breadcrumbs#11]
After installing laravel-breadcrumbs and adding a single breadcrumb to config/breadcrumbs.php, I get "A facade root has not been set.". 

Tried adding it to my app aliases but that made no difference.

Any ideas?

**Comment by shengslogar** [comment]
Hmm, my guess is something to do with how Laravel boots up. You shouldn't be adding breadcrumbs to your config file.

https://github.com/diglactic/laravel-breadcrumbs#2-define-your-breadcrumbs

Try adding to `routes/breadcrumbs.php` and see if that does the trick.
