### ISSUE TITLE
Breadcrumb not found with name ...

### ISSUE THREAD

**Issue by Schwenniii** [diglactic/laravel-breadcrumbs#13]
I have migrated from DaveJamesMiller\Breadcrumbs

on Local Develoment it runs fine but on Production he knows no breadcrump since i migrate.
the breadcrumbs are defined under default/breadcrumbs.php

I have try:
" If not, try running php artisan config:clear (or manually delete bootstrap/cache/config.php) or update the path in config/breadcrumbs.php.."

delete all cached views
delete routes cache

but nothing helps

Any Ideaa what the Problem is?

**Comment by shengslogar** [comment]
Are you getting any errors? Can you post a copy of your config and breadcrumb files?

**Comment by Schwenniii** [comment]
sorry for the late answer i was sick

yes i get "Breadcrumb not found with name "category""

on routes/breadcrumbs.php

/**
 * Category
 */
Breadcrumbs::for('category', function($trail, $category){
    $trail->parent('category_all');
    $trail->push(__($category->name), route('category', ['name' => $category->name, 'id', $category->id]));
});


config/breadcrumbs.php is default nothing changed

'files' => base_path('routes/breadcrumbs.php'),

**Comment by shengslogar** [comment]
Hm, can you show me how you're calling `Breadcrumbs::render`?

**Comment by Schwenniii** [comment]
on show.blade.php

@section('breadcrumbs', Breadcrumbs::render('category', $category))


and the section on detail

{{-- Breadcumbs Section --}}
    <div class="container" id="breadcrumbs">
        @yield('breadcrumbs')
    </div>

**Comment by Schwenniii** [comment]
strange i have made a routine composer update and it's work now nothing else changed

Thx for the help. Bottom the composer log

Lock file operations: 0 installs, 16 updates, 0 removals
  - Upgrading laravel/framework (v6.20.5 => v6.20.7)
  - Upgrading maximebf/debugbar (v1.16.3 => v1.16.4)
  - Upgrading nikic/php-parser (v4.10.2 => v4.10.3)
  - Upgrading paragonie/sodium_compat (v1.13.0 => v1.14.0)
  - Upgrading phar-io/manifest (1.0.3 => 2.0.1)
  - Upgrading phar-io/version (2.0.1 => 3.0.3)
  - Upgrading phpunit/php-code-coverage (7.0.13 => 7.0.14)
  - Upgrading phpunit/php-token-stream (3.1.2 => 4.0.4)
  - Upgrading phpunit/phpunit (8.5.11 => 8.5.13)
  - Upgrading swiftmailer/swiftmailer (v6.2.3 => v6.2.4)
  - Upgrading web-token/jwt-core (v2.2.5 => v2.2.6)
  - Upgrading web-token/jwt-key-mgmt (v2.2.5 => v2.2.6)
  - Upgrading web-token/jwt-signature (v2.2.5 => v2.2.6)
  - Upgrading web-token/jwt-signature-algorithm-ecdsa (v2.2.5 => v2.2.6)
  - Upgrading web-token/jwt-util-ecc (v2.2.5 => v2.2.6)
  - Upgrading yajra/laravel-datatables-oracle (v9.15.0 => v9.15.2)

**Comment by shengslogar** [comment]
Sometimes running `composer dump-autoload` (which `composer update` does) will do the trick! Glad you got this working.
