### ISSUE TITLE
Class not found

### ISSUE THREAD

**Issue by webhostingsrbijaRS** [diglactic/laravel-breadcrumbs#18]
Hello i installed, tried but i get error: Class Breadcrumbs not  found in view blade file.
I tried: [#class-breadcrumbs-not-found](https://github.com/diglactic/laravel-breadcrumbs#class-breadcrumbs-not-found)

`Discovered Package: diglactic/laravel-breadcrumbs`

routes/breadcrumbs.php
```
Breadcrumbs::for('home', function ($trail) {
    $trail->push('Home', route('home'));
});
```
I tried to set in controller like:
```
$data['breadcrumbs'] = Breadcrumbs::generate();
view("view.blade.php",["data"=>$data]);
```
Then i get `Class 'Diglactic\Breadcrumbs\Breadcrumbs' not found`
what i also can do?

Laravel 8
PHP 7.4
Apache
OS CentOS 8

**Comment by shengslogar** [comment]
Try running `composer dump-autoload` and see if the error persists.

**Comment by webhostingsrbijaRS** [comment]
The same. Also tried clear cache

```
composer dump-autoload
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: barryvdh/laravel-dompdf
Discovered Package: diglactic/laravel-breadcrumbs
```

**Comment by shengslogar** [comment]
Hm, not sure what's happening here. If you feel comfortable sharing your project code (private, can add me temporarily), I can try and debug for you.

When you get `Class 'Diglactic\Breadcrumbs\Breadcrumbs' not found` inside your controller, are you importing it with a `use Diglactic\Breadcrumbs\Breadcrumbs` statement?

**Comment by webhostingsrbijaRS** [comment]
Unfortunately there are a lot of sensitive data so i can't share source code. 
Yes `use Diglactic\Breadcrumbs\Breadcrumbs;` is at top

```
namespace App\Http\Controllers;

use App\Models\DataModel;
use Diglactic\Breadcrumbs\Breadcrumbs;
use Illuminate\Http\Request;
use App\Http\Controllers\MailController;
use Illuminate\Support\Facades\Auth;
```

Even (PHPStorm) see that class (screenshot below)
[screenshot1](https://ibb.co/4F5tv2B)
[screenshot2](https://ibb.co/3fpCJDx)

**Comment by shengslogar** [comment]
What `composer --version` are you running?

**Comment by webhostingsrbijaRS** [comment]
`composer --version
Composer version 2.0.9 2021-01-27 16:09:27
`

**Comment by shengslogar** [comment]
The other thing you might try is `rm -rf` your `vendor` folder (maybe even `composer.lock`) and running `composer install` again. Let me double-verify on my machine with Composer 2.

**Comment by shengslogar** [comment]
Working for me on Composer 2. You're running v6.1.0 of breadcrumbs? I can't really help further without seeing your code, but you might try creating a brand new Laravel project and seeing if the problem persists. That would tell you if something outside of this package is causing this.

**Comment by webhostingsrbijaRS** [comment]
Tried also with vender and composer.lock. First i had composer 1 but i updated i tought that will fix this. 
OK  thank you for your time.

**Comment by mariapaulinar** [comment]
This still persist for me!

**Comment by shengslogar** [comment]
@mariapaulinar This hasn't been a reproducible issue. What version of the following are you using?

- Composer
- PHP
- Laravel
- diglactic/laravel-breadcrumbs

Can you share code that caused this exception to be thrown?

**Comment by mariapaulinar** [comment]
Hello. Here my config:

Composer:
![image](https://user-images.githubusercontent.com/1920342/113495858-f4b07e00-94b9-11eb-8dac-091f50a19c2e.png)

PHP: 
![image](https://user-images.githubusercontent.com/1920342/113495866-06922100-94ba-11eb-8224-dc78b3701728.png)

Laravel:
![image](https://user-images.githubusercontent.com/1920342/113495882-245f8600-94ba-11eb-89f3-0818bd274816.png)

Laravel Breadcrumb:
![image](https://user-images.githubusercontent.com/1920342/113495894-3b05dd00-94ba-11eb-9986-79b05a750318.png)

**Comment by shengslogar** [comment]
@mariapaulinar Thanks. What are the steps leading up to to this exception being thrown?

**Comment by mariapaulinar** [comment]
My error! I was'nt using the namespace on breadcrumbs.php. Sorry!
