### ISSUE TITLE
Breadcrumbs macro not printing

### ISSUE THREAD

**Issue by hasanakhtar** [diglactic/laravel-breadcrumbs#2]
The macro that I am using and checked each variable which is passing fine. Its just that the breadcrumbs are not getting 'printed'.

using this in the view:

  {{Breadcrumbs::resource('lawfirm', 'Law Firm')}}

`Breadcrumbs::macro('resource', function ($name, $title) {

   
    Breadcrumbs::for("$name.index", function ($trail) use ($name, $title) {
        $trail->parent('home');
        $trail->push($title, route("$name.index"));
    });

   
    Breadcrumbs::for("$name.create", function ($trail) use ($name) {
        $trail->parent("$name.index");
        $trail->push('New', route("$name.create"));
    });

  
    Breadcrumbs::for("$name.show", function ($trail) use ($name) {
        $trail->parent("$name.index");
        $trail->push($name->id, route("$name.show", [$name->id]));
    });

    Breadcrumbs::for("$name.edit", function ($trail) use ($name) {
        $trail->parent("$name.index");
        $trail->push('Edit', route("$name.edit", [$name->id]));
    });
});
`
Any heads up will be greatly appreciated.

**Comment by shengslogar** [comment]
Can you show me your Blade code? Where are you trying to render the breadcrumbs but it's not working? Are you getting any errors?

https://github.com/diglactic/laravel-breadcrumbs#4-output-the-breadcrumbs

**Comment by hasanakhtar** [comment]
I am using the following code in the views/lawfirms/index.blade.php ,views/lawfirms/edit.blade.php,views/lawfirms/show.blade.php, etc on all resource routes views

`{{Breadcrumbs::resource('lawfirm', 'Law Firm')}}`

The exists check prints 1 (true) on the page `Breadcrumbs::exists(string $name)`

(https://github.com/davejamesmiller/laravel-breadcrumbs#api-reference)

**Comment by shengslogar** [comment]
Given your macro, `Breadcrumbs::resource` defines the breadcrumb, and should only be called once in your entire application. Once the breadcrumb is defined, you’ll need to output it in your Blade file using the `Breadcrumbs::render` method.

If you’re still having trouble, please post your entire Blade file.

**Comment by hasanakhtar** [comment]
Here is the content of my routes/breadcrumbs.php

`Breadcrumbs::for ('home', function ($trail) {
    $trail->push('Home', route('home'));
});


Breadcrumbs::macro('resource', function ($name, $title) {


    Breadcrumbs::for("$name.index", function ($trail) use ($name, $title) {
        $trail->parent('home');
        $trail->push($title, route("$name.index"));
    });

  
    Breadcrumbs::for("$name.create", function ($trail) use ($name) {
        $trail->parent("$name.index");
        $trail->push('New', route("$name.create"));
    });


    Breadcrumbs::for("$name.show", function ($trail) use ($name) {
        $trail->parent("$name.index");
        $trail->push($name->id, route("$name.show", [$name->id]));
    });

   
    Breadcrumbs::for("$name.edit", function ($trail) use ($name) {
        $trail->parent("$name.index");
        $trail->push('Edit', route("$name.edit", [$name->id]));
    });
});
`

And here is the breadcrumb section of my blade file. The breadcrumbs are called only once on this file:
`// Tried this but output as "breadcrumb not found with name
{ {{ Breadcrumbs::render('lawareas', 'Areas of Law') }} 

// Tried this and it does not show any errors but still does not print any breadcrumbs
{{--               {{Breadcrumbs::resource('lawareas', 'Areas of Law')}}--}} 

// Tried this but outputs as '1'
                {{Breadcrumbs::exists('lawareas.index')}} `

**Comment by shengslogar** [comment]
When calling `Breadcrumbs::render`, you'll need to specify a specific name. Is it `lawareas.index`, `lawareas.create`...? If you leave it blank (default behavior), the library will automatically detect your current route. Also, you should call your `Breadcrumbs::resource` macro inside `routes/breadcrumbs.php`. Hope that helps.

(P.S. `Breadcrumbs::exists` is returning `1 == true` because that breadcrumb does, indeed, exist. That's working correctly!)

**Comment by hasanakhtar** [comment]
Thanks for the heads up! 
Working fine now! Many thanks.

Also thank you on behalf of the community for taking this package forward. Much appreciated!
