### ISSUE TITLE
How to remove the '-' after the name

### ISSUE THREAD

**Issue by donchoborisov** [diglactic/laravel-breadcrumbs#24]
Hi there, 

Is there any option to remove the ''-" after the name?

Thank you very much in advance

**Comment by donchoborisov** [comment]
![image](https://user-images.githubusercontent.com/48497063/115031484-1d744280-9ec0-11eb-8c0a-10c074bb5a5c.png)

**Comment by donchoborisov** [comment]
I fix the issue by removing the class active in bootstrap4.blade.php and i just replace that class with text-muted

`@unless ($breadcrumbs->isEmpty())

    <ol class="breadcrumb">
        @foreach ($breadcrumbs as $breadcrumb)

            @if ($breadcrumb->url && !$loop->last)
                <li class="breadcrumb-item "><a href="{{ $breadcrumb->url }}">{{ $breadcrumb->title }}</a></li>
            @else
                <li class="breadcrumb-item text-muted  ">{{ $breadcrumb->title }}</li>
            @endif

        @endforeach
    </ol>

@endunless`

**Comment by shengslogar** [comment]
Hmm... sounds like you're doing something special with Bootstrap to cause this behavior? There shouldn't be any special characters attached to breadcrumbs out of the box.

Glad you were able to figure it out either way.

https://getbootstrap.com/docs/4.0/components/breadcrumb/

**Comment by donchoborisov** [comment]
Nothing special so far :) 

Anyway thanks for your quick response and your help

**Comment by shengslogar** [comment]
If you figure out what's causing the issue, happy to take a closer look. Afaik this is not default Bootstrap 4 behavior.

**Comment by donchoborisov** [comment]
on of my pages
@extends('layouts.default')
@section('content')
 
 
 <section>
    <div class="container-fluid">
       
        <div class="row banner-policy justify-content-center align-items-center banner-heading "  style="height: 50vh;">
            <div class="col-sm-10 text-right">
                <h1 class="display-3 text-capitalize banner-heading "><span class="text-warning banner-s  ">Our Policies</span></h1>
                    
                    
                  
            </div>

        </div>
    </div>


  </section>
   
   {{ Breadcrumbs::render('policies') }}


   <section class="bg-light p-7 mt-5 ">
      <div class="container-fluid">
          <div class="row text-left text-secondary font-weight-bold">
              <div class="col-lg-10 policies col-sm-10 mx-auto border-bottom mt-3 mb-3 ">
                @foreach($policies as $policy)
                  <div class="shadow-sm bg-secondary pt-4 pb-4 rounded d-flex justify-content-between mb-3 ">

                 
                      
                      <h5 class="text-warning ml-4  ">{{$policy->name}}</h1>
                      <a target="_blank" rel="noopener noreferrer" href="{{Storage::url((json_decode($policy->file_path))[0]->download_link)}}"   class="mr-4 btn btn-sm btn-warning"><i class="fas  fa-cloud-download-alt"></i></a>
                    </div>
                    @endforeach

              </div>
          </div>


      </div>
  </section>  
@stop`
`


bootstrap 4 file
`
@unless ($breadcrumbs->isEmpty())

    <ol class="breadcrumb">
        @foreach ($breadcrumbs as $breadcrumb)

            @if ($breadcrumb->url && !$loop->last)
                <li class="breadcrumb-item  "><a href="{{ $breadcrumb->url }}">{{ $breadcrumb->title }}</a></li>
            @else
                <li class="breadcrumb-item text-muted  ">{{ $breadcrumb->title }}</li>
            @endif

        @endforeach
    </ol>

@endunless

`

**Comment by donchoborisov** [comment]
which part you want me to show you?

**Comment by shengslogar** [comment]
If swapping `class="active"` for `class="text-muted"` solved it, it's likely there's some CSS style overriding Bootstrap that's causing this issue. I probably can't solve this by looking over your Blade templates.

I would inspect the component in your browser and work backwards to figure this one out.

**Comment by donchoborisov** [comment]
Yes you are right maybe something is playing behind in my css i will double check this.
