### ISSUE TITLE
Breadcrumbs did not load/register

### ISSUE THREAD

**Issue by lloricode** [diglactic/laravel-breadcrumbs#26]
Hi!,

before we upgrade to laravel 8.42, its work perfectly,
but after upgrade to laravel 8.42, seems all breadcrumbs did not register

diglactic/laravel-breadcrumbs                      v6.1.1
Laravel Framework                                     v8.42.0
PHP                                                             7.4.18

**Comment by shengslogar** [comment]
Did you follow the [upgrade guide](https://github.com/diglactic/laravel-breadcrumbs/blob/main/UPGRADE.md)? Can you post a copy/screenshot of any exceptions that are being thrown, or does "seems all breadcrumbs did not register" mean nothing is showing at all?

**Comment by lloricode** [comment]
> Did you follow the [upgrade guide](https://github.com/diglactic/laravel-breadcrumbs/blob/main/UPGRADE.md)? Can you post a copy/screenshot of any exceptions that are being thrown, or does "seems all breadcrumbs did not register" mean nothing is showing at all?

we use this package long time ago since you maintain it, so it works perfectly.

and here the image
![Screenshot from 2021-05-19 08-23-08](https://user-images.githubusercontent.com/8251344/118739289-adb8f500-b87b-11eb-880a-c26c0b1cc7f8.png)

**Comment by lloricode** [comment]
@shengslogar things back to work after updating to laravel v8.42.1
