### ISSUE TITLE
Use package in laravel with Twig-Bridge

### ISSUE THREAD

**Issue by Scorpovi4** [diglactic/laravel-breadcrumbs#31]
Is this possible to use your package output to .twig template?

I've faced with problem of output in .twig template with this syntax `Breadcrumbs::render('home')` 
The rest is working well, could you help with this issue resolving?

**Comment by shengslogar** [comment]
@Scorpovi4 I've never used `.twig` files. My understanding is that's specific to Drupal? If so, that's outside the scope of a Laravel plugin like this, but feel free to open a PR if I'm wrong.

**Comment by Scorpovi4** [comment]
As in title, I have lagacy integrated Twig Bridge into the laravel on a project and I just need help to output plugin result ti twig if it's possible. Your plugin is fully compatible because 

I'm using it within laravel, but templates are .twig instead .blade. 

Problem in this part 
`Breadcrumbs::render('home')`, don't know how to call it within twig template.

**Comment by shengslogar** [comment]
Ah, missed that part.

I'm out of my depth here, but essentially you need the following native PHP:

```
<?php

echo Breadcrumbs::render('home');
```

If you can figure out how to convert that into Twig code you should be good to go.
