### ISSUE TITLE
Undefined type 'Diglactic\Breadcrumbs\Breadcrumbs'.

### ISSUE THREAD

**Issue by codewithdjaeger** [diglactic/laravel-breadcrumbs#32]
Hello, so, I'm trying to use your package. I followed every step of the getting started section. But, it's ended up being an undefined type even though I had the composer required it, updating it, and any advice you give in both of the troubleshooting section and issues. Also, the composer had the package discovered. But, still, it won't work.

Here is the problem:
![image](https://user-images.githubusercontent.com/85334514/129463555-06ecd0cc-d98c-4482-9b29-6c8515947b7e.png)

I've been publishing the config too:
![image](https://user-images.githubusercontent.com/85334514/129463586-27f6e0b2-490d-48ed-acfd-9d373ba7f4eb.png)

Had the composer discovered it:
![image](https://user-images.githubusercontent.com/85334514/129463600-3eeb2237-76b1-4557-810e-6c2fd4f26685.png)

I really look forward to your help, thanks

**Comment by shengslogar** [comment]
That’s a problem with your IDE configuration with Intelephense and outside the scope of this project. You might take a look at this:

https://stackoverflow.com/a/59266972
