### ISSUE TITLE
Feature idea: `Route::breadcrumbs()` macro

### ISSUE THREAD

**Issue by inxilpro** [diglactic/laravel-breadcrumbs#33]
Hi there,

We're using `laravel-breadcrumbs` in our application, and we've added a shorthand that allows us to register breadcrumbs on the route:

```php
Route::get('/users', [UsersController::class, 'index'])
  ->name('users.index')
  ->breadcrumbs('Users'); // <--

// Is the same as:
Breadcrumbs::for('users.index', function(Trail $trail) {
  $trail->push('Users', route('users.index'));
});

Route::get('/users/create', [UsersController::class, 'create'])
  ->name('users.create')
  ->breadcrumbs('Add a User', '.index'); // <--

// Is the same as:
Breadcrumbs::for('users.create', function(Trail $trail) {
  $trail->parent('users.index');
  $trail->push('Add a User', route('users.create'));
});

Route::get('/users/{user}', [UsersController::class, 'show'])
  ->name('users.show')
  ->breadcrumbs(fn(User $user) => $user->name, '.index'); // <--

// Is the same as:
Breadcrumbs::for('users.show', function(Trail $trail, User $user) {
  $trail->parent('users.index');
  $trail->push($user->name, route('users.index'));
});
```

If you pass a string to the first argument, that's considered the breadcrumb title. If it's a closure, the closure is called with the route parameters and can return a dynamic title.

If you pass a string starting with a dot `.` to the second argument (`parent`) it uses whatever prefix the current route has (for example, on a route named `"a.b.c.d"`, passing `".foo"` would result in `"a.b.c.foo"`). Otherwise, it assumes it's a fully registered breadcrumb name.

It would take me a little while to clean it up an extract it as a PR. If I were to do so, is this something you're interested in merging into the package?

**Comment by ShengSlogar** [comment]
Oh, that's nifty! Not sure how I feel about mixing content and logic (especially if you localized your app and referenced translations), although you could argue we're already doing that with the breadcrumbs config. Would we have to build in anything special to support `php artisan route:cache`?

I've been thinking on how to clean up route mapping overall; I know my breadcrumbs files tend to get pretty large and unmanageable, which I'm guessing has been the case for you as well. One half-baked idea has been:
```
[
     'users' => [
          'index' => 'Users',
          [
               'show' => 'Show',
                'create' => 'Create',
               // ...
          ]
     ],
    'foo.bar.baz' => 'Some Non-Resourceful Route'
]
```
🤷 

Thanks for starting this conversation -- and let's keep it going. I want to keep this issue this open while I percolate on ideas (and hopefully get some community input, also).

**Comment by inxilpro** [comment]
Yeah, we have a `php artisan breadcrumbs:cache` and `breadcrumbs:clear` command in place as well.

I *much* prefer defining them in the routes file itself, and I don't think there's anything stopping you from using localizations/etc with this strategy. Mull it over and let me know :)

**Comment by ShengSlogar** [comment]
This is growing on me, but I have a few more questions (especially never having worked with route macros before):

1. How do we reproduce `$trail->parent('foo.bar', $some, $additional, $params)` with your change?
2. Would we need to build in additional logic to support resourceful routes? (`Route::resource('foo')->breadcrumbs(...)`)
3. Does this work within `Route::group`s?
4. I think the only thing I'd like to remove is the parent shorthand. `.index` feels too ambiguous to me, and I'd prefer the fully qualified `users.index` every time.

Trying to make sure I ask all the things before you go through the trouble of a PR. Thanks! ☺️

**Comment by inxilpro** [comment]
> How do we reproduce `$trail->parent('foo.bar', $some, $additional, $params)` with your change?

You can pass a closure to either argument to have full control over building up the breadcrumbs if you need it. In this way, it essentially becomes a shorthand for the `Breadcrumbs::for()` syntax without the other convenience.

> Would we need to build in additional logic to support resourceful routes? (`Route::resource('foo')->breadcrumbs(...)`)

Yep. That's outside the scope of our implementation. I don't think it's necessary. This is just added functionality, not a replacement for the existing API.

> 3. Does this work within `Route::group`s?

Yep. The group attributes are applied when the route is instantiated, so by the time you're chaining `->breadcrumb()`, all of the group context is already applied.

> I think the only thing I'd like to remove is the parent shorthand. `.index` feels too ambiguous to me, and I'd prefer the fully qualified `users.index` every time.

Honestly, I think the `.index` shorthand is probably the best part of this whole implementation. If you want to be explicit, you're better off using `Breadcrumbs::for`. In the end, I think the DX upside is **so** worth it.

That said, I think the functionality can probably implemented as a separate package and be opt-in. That might be a better approach.

**Comment by ShengSlogar** [comment]
Thanks for that! Your way sounds pretty opinionated (which is great! It's clear you've put thought into it), so I really like your idea of a separate package to start.

If you end up creating it as a plugin (versus an entire fork), I'd link to it from this project's README. If you'd like to see that happen, feel free to keep this issue open until then or open a new one later. 🥂

**Comment by innocenzi** [comment]
Hey @inxilpro, have you made a package for this? I came to the issues for this exact same idea so I'm glad to see I wasn't the only one. If not a package, can you share your current implementation?

**Comment by innocenzi** [comment]
Thanks! I'll give that a try.
