### ISSUE TITLE
Publishable views

### ISSUE THREAD

**Issue by lasseeee** [diglactic/laravel-breadcrumbs#35]
Would it be possible to make the views publishable, so that [Bootstrap 2 and 3 support could be added back in](https://github.com/diglactic/laravel-breadcrumbs/commit/2aeacfaa33f3b13400be0bdf3bb2357f7b78548c) outside of the package going forward from v7 where it was removed? Ref https://github.com/diglactic/laravel-breadcrumbs/issues/34

**Comment by ShengSlogar** [comment]
You're more than welcome to copy the templates removed in that commit and reference them as described in the [README, Custom Templates](https://github.com/diglactic/laravel-breadcrumbs#custom-templates).

If you're looking to continue using the `breadcrumbs::bootstrap3` syntax, you _should_ be able to manually publish those files into `/resources/views/vendor/bootstrap/` and reference them that way.

**Comment by lasseeee** [comment]
Unable to publish anything but the config, but I'll just recreate and ref the view manually as per the README. Thanks for the swift reply and heads-up, as well as taking this package forward 👍

**Comment by ShengSlogar** [comment]
Yeah, only the config is publishable. If views _were_ published, they would go into the `resources/views/vendor/breadcrumbs/` (sorry, typoed earlier).

Even though we're _not_ publishing views, this line of code should already support that functionality: 
https://github.com/diglactic/laravel-breadcrumbs/blob/0a14e8785fa9423c878edd3975af2a92dfcdaf42/src/ServiceProvider.php#L49

So: try creating a `resources/views/vendor/breadcrumbs/bootstrap3.blade.php` in your local project, and referencing `breadcrumbs::bootstrap3` should then work.

**Comment by lasseeee** [comment]
Works like a charm! 🙌
