### ISSUE TITLE
Model not found

### ISSUE THREAD

**Issue by MubinSayed** [diglactic/laravel-breadcrumbs#36]
Argument 2 passed to Diglactic\Breadcrumbs\ServiceProvider::{closure}() must be an instance of App\Models\WaterRateMaster, string given, called in C:\Users\Admin\OneDrive\Documents\GitHub\pos-project\vendor\diglactic\laravel-breadcrumbs\src\Generator.php on line 64 (View: C:\Users\Admin\OneDrive\Documents\GitHub\pos-project\resources\views\admin\layout\breadcrum.blade.php) 
![image](https://user-images.githubusercontent.com/9677258/134769968-bbe16bdc-0986-42b3-af92-05da65ac193f.png)

![image](https://user-images.githubusercontent.com/9677258/134769915-15f6e922-69b0-471c-b372-8acc3a7443f8.png)

This error comes when ID doesn't exists in database.

**Comment by ShengSlogar** [comment]
This isn't a problem with this library. I've only ever seen this issue happen when [route-model binding](https://laravel.com/docs/8.x/routing#implicit-binding) isn't working correctly at your routes-file level.
