### ISSUE TITLE
can support laravel 9

### ISSUE THREAD

**Issue by hosamalzagh** [diglactic/laravel-breadcrumbs#42]
please can support laravel 9

`  Illuminate\Contracts\Container\BindingResolutionException 

  Target class [DaveJamesMiller\Breadcrumbs\BreadcrumbsManager] does not exist.

  at vendor/laravel/framework/src/Illuminate/Container/Container.php:879
    875▕ 
    876▕         try {
    877▕             $reflector = new ReflectionClass($concrete);
    878▕         } catch (ReflectionException $e) {
  ➜ 879▕             throw new BindingResolutionException("Target class [$concrete] does not exist.", 0, $e);
    880▕         }
    881▕ 
    882▕         // If the type is not instantiable, the developer is attempting to resolve
    883▕         // an abstract type such as an Interface or Abstract Class and there is

      +24 vendor frames 
  25  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1`

**Comment by shengslogar** [comment]
Laravel 9 is fully supported.

```
$ composer install
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: diglactic/laravel-breadcrumbs

$ composer show laravel/framework   
name     : laravel/framework
descrip. : The Laravel Framework.
keywords : framework, laravel
versions : * v9.0.0
```

You're still referencing the `DaveJamesMiller` namespace that was removed in v7. You'll need to replace `DaveJamesMiller\Breadcrumbs\BreadcrumbsManager` with `Diglactic\Breadcrumbs\Manager`. [See the upgrade guide.](https://github.com/diglactic/laravel-breadcrumbs/blob/main/UPGRADE.md)
