### ISSUE TITLE
How to split the breadcrumbs.php file across multiple files?

### ISSUE THREAD

**Issue by kerrinhardy** [diglactic/laravel-breadcrumbs#45]
In my application there are a number of pages for each model (the standard CRUD pages, plus additional views and reports).  Before it becomes too unwieldily, I was looking to split it up into multiple files - all called from breadcrumbs.php.

A simple require / include statement is not working (in a Laravel project)?

Has anyone done this before?

**Comment by shengslogar** [comment]
I don’t think I’ve personally ever used includes (I would instead break things out into multiple classes with a single static method like `PostBreadcrumbs::register()` that can be called from the root breadcrumbs file using namespaced imports) but I don’t know of any reason why an include wouldn’t work. Is there a specific error you’re getting when you try this?

**Comment by kerrinhardy** [comment]
Thanks for the update.  I started going down that path, and then looking at the config file I see there is an option to use a wildcard:
`'files' => glob(base_path('breadcrumbs/*.php')),`

Turns out it was easy to do.  Thank you for a great plugin!

**Comment by superjavi-nys** [comment]
> I don’t think I’ve personally ever used includes (I would instead break things out into multiple classes with a single static method like `PostBreadcrumbs::register()` that can be called from the root breadcrumbs file using namespaced imports) but I don’t know of any reason why an include wouldn’t work. Is there a specific error you’re getting when you try this?

Hi, breadcrumbs work fine, but I use Modules but I need to create in each module own breadcrumbs files for reason are the developers make owns modules and it's to complicate only have one file in main routes

How make to load each breadcrumb file of each module??

<img width="150" alt="Image" src="https://github.com/user-attachments/assets/c16d6dae-517d-42fd-94bf-89802b887a2c" />

**Comment by shengslogar** [comment]
@superjavi-nys globs (as mentioned in the previous comment) sound like a great solution for you here!
