### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by precamp-io** [diglactic/laravel-breadcrumbs#50]
Thanks for building such and amazing addition. I am using translation in my project like this {{__('Projects')}} how would this be incorporated so that breadcrumbs can take translations into consideration? {{ Breadcrumbs::render() }}

Breadcrumbs::for('projects.index', function (BreadcrumbTrail $trail): void {
    $trail->push('Projects', route('projects.index'));
});

**Comment by shengslogar** [comment]
`__` is the name of a function. You can inject that into Breadcrumbs (or anywhere else in your Laravel project) like this:

```
Breadcrumbs::for('projects.index', function (BreadcrumbTrail $trail): void {
     $trail->push(__('Projects'), route('projects.index'));
});
```
