### ISSUE TITLE
Be careful with breadcrumbs on 403 page and using authorization policies

### ISSUE THREAD

**Issue by s-o-f** [diglactic/laravel-breadcrumbs#54]
Let's pretend you are using custom 403.blade.php view template with breadcrumbs on it.
If some policy will deny access to requested SomeModel your breadcrumbs still will contain SomeModel title, which current user should not see.

So for resource example code should be smth like this:
```
// Home > Blog > Post 123
Breadcrumbs::for("{$name}.show", function (BreadcrumbTrail $trail, SomeModel $model) use ($name) {
	$trail->parent("{$name}.index");
	if (Auth::user()->can('view', $model)) { // you should check permission
		$trail->push($model->title, route("{$name}.show", $model));
	}
});
```

**Comment by shengslogar** [comment]
A better practice would be to completely disable breadcrumbs on any 403 page, whether that's directly through your 403 template or by wrapping `Breadcrumbs::render()` with [something like this](https://stackoverflow.com/a/63531921/2535504):

```
@unless (isset($exception) && $exception->getStatusCode() === 403)
    {{ Breadcrumbs::render() }}
@endunless
```

Closing as this is not unique to this package and is only informative.
