### ISSUE TITLE
Static invocation possible?

### ISSUE THREAD

**Issue by fbc** [diglactic/laravel-breadcrumbs#6]
With tabuna/breadcrumbs you can just use in a blade template partial:
```
@if(Breadcrumbs::has())
    @foreach (Breadcrumbs::current() as $crumbs)
        @if ($crumbs->url() && !$loop->last)
            <li class="breadcrumb-item">
                <a href="{{ $crumbs->url() }}">
                    {{ $crumbs->title() }}
                </a>
            </li>
        @else
            <li class="breadcrumb-item active">
                {{ $crumbs->title() }}
            </li>
        @endif
    @endforeach
@endif
```
and there is no need to visit each blade file to paste anything in. Would it be too difficult to adopt this approach? I love this package and all the great work your put into it, and it's still a time saver. I just wish it could save you an extra step.

**Comment by shengslogar** [comment]
Not sure I follow. You can configure your template by modifying the `view` config value, and assuming you name your breadcrumbs the same as your routes, can render breadcrumbs by calling `Breadcrumbs::render()` anywhere. How is what you’re suggesting different?

**Comment by fbc** [comment]
@shengslogar Thanks.. I didn't realize that it would dynamically look for the path.
