### ISSUE TITLE
Can't upgrade from 7 to 8 due to route domain parameter bug

### ISSUE THREAD

**Issue by mpie** [diglactic/laravel-breadcrumbs#63]
In commit: https://github.com/diglactic/laravel-breadcrumbs/commit/7c455480810eb196bc0339c06dc63062b7d35a46 there is a bug that has been introduced.

If you have a dynamic Route::domain(), the first argument in the `$params` (line 253) will always be null, which results in a wrong route parameter binding. 
parameters != parameterNames

Expected (and working):
<img width="684" alt="Screenshot 2023-03-06 at 01 27 27" src="https://user-images.githubusercontent.com/99145/222995036-8b0f97a9-24f8-4f2a-8195-559300dc74fd.png">

Actual (not working):
<img width="688" alt="Screenshot 2023-03-06 at 01 26 01" src="https://user-images.githubusercontent.com/99145/222995061-272354d5-2207-459e-a2f6-970f1c686ce4.png">

**Comment by shengslogar** [comment]
I couldn't reproduce this with a dynamic subdomain. My simulated tests show the same parameters returned by both both Breadcrumbs v7 and v8. You'll need to provide code snippets that produce this issue.

**Comment by mpie** [comment]
@shengslogar No worries. I'll close the issue since I can override the Manager class in the config. This way we can upgrade to Laravel 10 and BreadCrumbs 8

**Comment by shengslogar** [comment]
I don't understand that rationale, but whatever works for you. 👍
