### ISSUE TITLE
Too few arguments to function Diglactic\Breadcrumbs\ServiceProvider

### ISSUE THREAD

**Issue by kirkaracha** [diglactic/laravel-breadcrumbs#66]
I'm getting a "Too few arguments to function Diglactic\Breadcrumbs\ServiceProvider" that says 1 parameter was passed and 2 are expected, but my route only has one parameter.

The route works fine without adding the breadcrumb code.

route:
```
Route::prefix('knowledge-base')->group(function () {
    Route::get('/', [KnowledgeBaseController::class, 'index'])
        ->name('knowledge-base.index');

    Route::get('{category:slug}', [CategoryController::class, 'show'])
        ->name('knowledge-base.category.show');
});
```

routes.breadcrumbs.php:
```
Breadcrumbs::for('knowledge-base', function (BreadcrumbTrail $trail): void {
    $trail->parent('home');

    $trail->push('Knowledge Base', route('knowledge-base.index'));
});

Breadcrumbs::for('knowledge-base-category', function (BreadcrumbTrail $trail, Category $category) {
    $trail->parent('knowledge-base');

    $trail->push($category->name, route('knowledge-base.category.show', [
        'category' => $category
    ]));
});
```

Blade:
```
{{ Breadcrumbs::render('knowledge-base-category') }}
```

**Comment by shengslogar** [comment]
See https://github.com/diglactic/laravel-breadcrumbs#4-output.

Calling `Breadcrumbs::render('knowledge-base-category')` invokes `Breadcrumbs::for('knowledge-base-category', function (BreadcrumbTrail $trail, Category $category)`, which expects `Category $category` to be passed as a parameter.

`{{ Breadcrumbs::render('knowledge-base-category', $yourCurrentCategory) }}` should do the trick.

**Comment by kirkaracha** [comment]
Thanks!
