### ISSUE TITLE
Can we use a date string instead of post id in route url?

### ISSUE THREAD

**Issue by adam-godfrey** [diglactic/laravel-breadcrumbs#68]
Everything is working fine but this is just a query to see if we can us a date instead of an id to get the post.

I want a url like [example.com/blog/2023-05-31/this-is-a-test-post](url). I've seen it done on other sites but not sure if it can be done with tis pacakge.

A recap...

`{{ Breadcrumbs::render('blog.show', $blog) }}`

```
use App\Models\Blog;
use Diglactic\Breadcrumbs\Breadcrumbs;
use Diglactic\Breadcrumbs\Generator as BreadcrumbTrail;

// /Home > Blog
Breadcrumbs::for('blog.show', function (BreadcrumbTrail $trail, Blog $blog) {
    $trail->parent('blog.index');
    $trail->push($blog->title, route('blog.show', $blog));
}); 
```

```
public function show(Blog $blog)
{
        $blog->content = GeneralHelper::nl2p($blog->content);

        $pageSize = 6;
        $entries = Blog::all(); 
        $entries = CollectionHelper::paginate($entries, $pageSize);

        $popular = $entries->sortByDesc('views')
            ->take(5);

        $data = array(
            'blog' => $blog,
            'entries' => $entries,
            'popular' => $popular
        );

        return view('awents/blog-single')->with($data); 
}
```

```
Route::get('/blog', [BlogController::class, 'index'])->name('blog.index');
Route::get('/blog/{blog}/{slug?}', [BlogController::class, 'show'])->name('blog.show');
```

**Comment by shengslogar** [comment]
You may run into trouble with the non-uniqueness of date strings, but this is ultimately a Laravel problem. This package will play nice with whatever model Laravel throws its way.

Now that you're using Laravel's route model binding, you'll just need to figure out how to "resolve" your blog post model via your desired parameters.

See https://laravel.com/docs/10.x/routing#customizing-the-resolution-logic
