### ISSUE TITLE
Looks like: Incompatible with Livewire

### ISSUE THREAD

**Issue by entezarlifedesign** [diglactic/laravel-breadcrumbs#73]
Hello

After the complete execution, if one of the properties is updated, an error of the same property will be issued.
where is the problem from?
For example, I have a "name" property in the program. If this variable is updated, the following error is issued:

`Breadcrumb not found with name "livewire.update" (View: list-all-user.blade.php)`

**Comment by shengslogar** [comment]
Hi there, I don't personally have any experience with Livewire, so I'm afraid I can't be of much help here without a reproducible demo.

Based on what you wrote, two thoughts come to mind:

1. This error appears to stem from you trying to render breadcrumbs on the `livewire.update` route. If Livewire uses a set number of named routes to perform its internal updates, you might be able to exclude them specifically from where you're calling `Breadcrumbs::render`.
2. If you'd like to suppress this error altogether, you might look at setting `missing-route-bound-breadcrumb-exception` to `false` in your configuration file. See https://github.com/diglactic/laravel-breadcrumbs#route-binding-exceptions

I'm not sure how other Laravel packages approach this, but happy to consider any further feedback, suggestions, or a PR to make this less painful.

**Comment by DoneItInnovations** [comment]
Did it worked for any Livewire user?

**Comment by pablomadariaga** [comment]
Tengo la solución a este problema, extendemos una clase de `Diglactic\Breadcrumbs\Manager` y sobreescribimos el metodo `getCurrentRoute`, este es el contenido de mi clase:

```
<?php

namespace App;

use Diglactic\Breadcrumbs\Exceptions\UnnamedRouteException;
use Diglactic\Breadcrumbs\Manager;

class BreadcrumbManager extends Manager
{
    /**
     * Get the current route name and parameters.
     *
     * This may be the route set manually with the setCurrentRoute() method, but normally is the route retrieved from
     * the Laravel Router.
     *
     * #### Example
     * ```php
     * [$name, $params] = $this->getCurrentRoute();
     * ```
     *
     * @return array A two-element array consisting of the route name (string) and any parameters (array).
     * @throws \Diglactic\Breadcrumbs\Exceptions\UnnamedRouteException if the current route doesn't have an associated
     *                                                                 name.
     */
    protected function getCurrentRoute(): array
    {
        // Manually set route
        if ($this->route) {
            return $this->route;
        }

        // Determine the current route
        $route = $this->router->current();
        if ($route->getName() == 'livewire.update') {
            $route = previousRoute($this->router);
        }

        // No current route - must be the 404 page
        if ($route === null) {
            return ['errors.404', []];
        }

        // Convert route to name
        $name = $route->getName();

        if ($name === null) {
            throw new UnnamedRouteException($route);
        }

        // Get the current route parameters
        $params = array_values(array_map(function ($parameterName) use ($route) {
            return $route->parameter($parameterName);
        }, $route->parameterNames()));

        return [$name, $params];
    }
}
```


como pueden ver se está usando una función `previousRoute($this->router);` si la solicitud actual proviene de livewire, para obtener la ruta de donde proviene la solicitud, en este caso la ruta antes de livewire/update, así solucionamos nuestro problema, basicamente  ignorando las solicitudes que provienen de livewire. La función previousRoute:


```
if (!function_exists('previousRoute')) {
    /**
     * Generate a route name for the previous request.
     *
     * @param Router $router
     * @return \Illuminate\Routing\Route|null
     */
    function previousRoute(\Illuminate\Routing\Router $router): \Illuminate\Routing\Route|null
    {
        $previousRequest = request()->create(url()->previous());

        try {
            $routeName = $router->getRoutes()->match($previousRequest);
        } catch (NotFoundHttpException $exception) {
            return null;
        }

        return $routeName;
    }
}
```

**Comment by shengslogar** [comment]
@pablomadariaga Why are you trying to render breadcrumbs on a `livewire.update` request? When is this normally called within a Livewire page lifecycle? I believe [my original reply](https://github.com/diglactic/laravel-breadcrumbs/issues/73#issuecomment-1765124094) is still relevant.

If you (or anyone else) is able to introduce this in such a way that it doesn't rely purely on a string match of `"livewire.update"`, I would consider a PR. If not, I would also be open to adding a note to the README once I understand what the challenge is here.

**Comment by pablomadariaga** [comment]
livewire.update is the default name of the livewire update path, but if you want to validate dynamically we can use the following condition:

```
if (request()->hasHeader('X-Livewire') || $route->named('*livewire.update')) {
             $route = previousRoute($this->router);
}
```

Livewire provides a method to validate if it is a request created by livewire: isLivewireRequest()

![image](https://github.com/diglactic/laravel-breadcrumbs/assets/69119357/9f06f198-95e1-4905-ba8d-5243282176ee)

And another to validate if the route name too

![image](https://github.com/diglactic/laravel-breadcrumbs/assets/69119357/0d194989-6c9b-4a6c-a97e-305be52365e9)

Here is the official livewire documentation

I think now we can consider a PR

https://livewire.laravel.com/docs/installation#configuring-livewires-update-endpoint

This is how the updated code would look

```
/**
     * Get the current route name and parameters.
     *
     * This may be the route set manually with the setCurrentRoute() method, but normally is the route retrieved from
     * the Laravel Router.
     *
     * #### Example
     * ```php
     * [$name, $params] = $this->getCurrentRoute();
     * ```
     *
     * @return array A two-element array consisting of the route name (string) and any parameters (array).
     * @throws \Diglactic\Breadcrumbs\Exceptions\UnnamedRouteException if the current route doesn't have an associated
     *                                                                 name.
     */
    protected function getCurrentRoute(): array
    {
        // Manually set route
        if ($this->route) {
            return $this->route;
        }

        // Determine the current route
        $route = $this->router->current();
        if (request()->hasHeader('X-Livewire') || $route->named('*livewire.update')) {
            $route = previousRoute($this->router);
        }

        // No current route - must be the 404 page
        if ($route === null) {
            return ['errors.404', []];
        }

        // Convert route to name
        $name = $route->getName();

        if ($name === null) {
            throw new UnnamedRouteException($route);
        }

        // Get the current route parameters
        $params = array_values(array_map(function ($parameterName) use ($route) {
            return $route->parameter($parameterName);
        }, $route->parameterNames()));

        return [$name, $params];
    }
```

**Comment by shengslogar** [comment]
@pablomadariaga 

> livewire.update is the default name of the livewire update path

What happens if you don't render breadcrumbs in your Blade file when `livewire.update` is being called? Does this cause the UI to break? [What about if you set `missing-route-bound-breadcrumb-exception` to `false`?](https://github.com/diglactic/laravel-breadcrumbs/issues/73#issuecomment-1765124094)

Your code looks headed in the right direction, but this is still a very specific use-case. For me to consider a PR, I'd want to:

1. See a full example repro of how this is breaking when used with Livewire. So far all I've gotten are snippets, but no one has posted complete code that indicates this is indeed a Breadcrumbs-specific problem that can't be worked around easily.
2. Make a case for why this should be solved at the Breadcrumbs level. For example, if there are other Laravel packages that have similar conflicting behavior. (If so, it would also make sense to build this functionality out in a reusable way.)
3. Identify a way of determining if Livewire is installed as a package rather than relying on potentially-flaky signals. Alternatively, something like a config file option might make sense.
4. Tests that validate a route registered as `livewire.update` behaves accordingly when Livewire is (1) installed and (2) not installed. [See the full contribution guidelines.](https://github.com/diglactic/laravel-breadcrumbs?tab=readme-ov-file#contributing)

Feel free to continue the discussion here or open a PR if you feel you're able to address all the items above.

**Comment by oskarhertzman** [comment]
Worth nothing, when i triggered livewire update calls, my params for my breadcrumbs stopped working and crashed with error `Attempt to read property "name" on string
,` for example my facility breadcrumb (`$trail->push($facility->name)`)

```php
// Facilities
Breadcrumbs::for('view.facilities', function (BreadcrumbTrail $trail) {
    $trail->push(ucfirst(__('app.info.facilities')), route('view.facilities'));
});

// Facility
Breadcrumbs::for('view.facility', function (BreadcrumbTrail $trail, $facility) {
    $trail->parent('view.facilities');
    $trail->push($facility->name, route('view.facility', $facility));
});

// Edit facility
Breadcrumbs::for('edit.facility', function (BreadcrumbTrail $trail, $facility) {
    $trail->parent('view.facility', $facility);
    $trail->push(ucfirst(__('app.info.edit')), route('edit.facility', $facility));
});
```

This is due to when livewire made an update call, instead of, for example returning the instance of the facility or organisation (which it normally does if defined in `mount()` as a param) it returns the uuid instead, (assuming it fallbacks and looks in the URL?)

I added a little helper method `getRouteParamsAfterLivewireCall` which fetches the relevant model for my view. e.g `/facilities/{UUID}/edit`


```php
protected function getCurrentRoute(): array {
        // Manually set route
        if ($this->route) {
            return $this->route;
        }

        // Determine the current route
        $route = $this->router->current();
        if (request()->hasHeader('X-Livewire') || $route->named('*livewire.update')) {
            $route = $this->previousRoute($this->router);
        }

        // No current route - must be the 404 page
        if ($route === null) {
            return ['errors.404', []];
        }

        // Convert route to name
        $name = $route->getName();

        if ($name === null) {
            throw new UnnamedRouteException($route);
        }

        // Get the current route parameters
        $params = array_values(array_map(function ($parameterName) use ($route) {
            $param = $route->parameter($parameterName);
            // Hacky workaround...
            if (is_string($param)) {
                $param = $this->getRouteParamsAfterLivewireCall($parameterName, $param);
            }

            return $param;
        }, $route->parameterNames()));

        return [$name, $params];
    }

    private function getRouteParamsAfterLivewireCall(string $parameterName, string $param): ?Collection {
        return match ($parameterName) {
            'organisation' => Organisation::find($param),
            'facility' => Facility::find($param),
            default => null,
        };
    }
```
