### ISSUE TITLE
Incompatibility with Self-Healing URLs for Combined Slug and ID Format

### ISSUE THREAD

**Issue by bridgeyuwa** [diglactic/laravel-breadcrumbs#83]
I am encountering an issue with Diglactic Breadcrumbs when used in conjunction with the [self-healing-urls](https://github.com/lukeraymonddowning/self-healing-urls) package. My application uses a combined slug and ID format for routing, which causes conflicts with the breadcrumbs generation.

**Problem:**

When self-healing URLs modifies the URL format to include both a slug and an ID 
Example:  ` id (PK): MIT`, `slug: massachusetts-institute-of-technology`.  
then `http://mydomain.dev/MIT/programs` becomes `http://mydomain.dev/massachusetts-institute-of-technology-MIT/programs`,
the breadcrumbs  fail to generate correctly. The error received is:

`Missing required parameters for [Route: institutions.programs] [URI: institutions/{institution}/programs] [Missing parameters: institution].`

**Current Setup:**

**Route Definition:**
```
Route::get('/institutions/{institution}/programs', [InstitutionController::class, 'showPrograms'])
    ->name('institutions.programs');
```

**Breadcrumbs Definition:**
```
// Institutions
Breadcrumbs::for('institutions.index', function (BreadcrumbTrail $trail) {
    $trail->parent('home');
    $trail->push('Institutions', route('institutions.index'));
});

//institution programs
Breadcrumbs::for('institutions.programs', function (BreadcrumbTrail $trail, $institution) {
    $trail->parent('institutions.show', $institution);
    $trail->push($institution->name . ' Programmes', route('institutions.programs', [$institution]));
});
```

**Expected Behavior:**

The breadcrumbs should correctly parse the combined slug and ID, and generate valid URLs for navigation without missing parameters.

**Steps to Reproduce:**

1. Configure [self-healing-urls](https://github.com/lukeraymonddowning/self-healing-urls)  to use combined slug and ID format.
2. Set up Diglactic Breadcrumbs with the appropriate breadcrumb definitions.
3. Visit a route using the combined slug format.
4. Observe the error in breadcrumb generation.

**Suggested Solution:**

Consider adding support or a configuration option in Diglactic Breadcrumbs to handle combined slug and ID formats, or provide guidance on how to manage such configurations.

Thanks.

**Comment by shengslogar** [comment]
What is the method signature of `showPrograms`?

**Comment by shengslogar** [comment]
Hm, that looks correct.

The error you're getting (`Missing required parameters for [Route: institutions.programs]`) is coming from within Laravel. You would get this same error if you called `route('institutions.programs')` without the `$institution` variable.

Your route-model binding appears to be wired up correctly, but for some reason it seems it isn't making its way inside your breadcrumbs method at this line:

```
$trail->push($institution->name . ' Programmes', route('institutions.programs', [$institution]));
// I would try `dd($institution)` here to see what you get
```

Feel free to post your full stack trace and/or a fully reproducible code example, but from what I can tell this is not an issue with this package.

**Comment by shengslogar** [comment]
I guess I don't understand how `$institution` becomes unavailable when you're using `self-healing-urls`. Assuming the package is still loading the same route and controller method, if `$institution` is unavailable at the breadcrumbs level it should also be unavailable at the controller method level, breaking the method altogether.

Happy to take a closer look at this if you set up a repro.

**Comment by shengslogar** [comment]
I'm not quite sure why specifying the parameter as an array ended up working without seeing your `institutions.show` breadcrumb and route, but I'm glad you figured it out!
